Vagrant.configure("2") do |config|

	config.vm.define :cell do |cell|
		cell.vm.box = "precise64"
		cell.vm.box_url = "http://files.vagrantup.com/precise64.box"
		cell.vm.network :forwarded_port, guest: 3000, host: 3000
		cell.vm.network :forwarded_port, guest: 28017, host: 28017
		cell.vm.synced_folder "../src", "/cell"
		
		cell.vm.provision :chef_solo do |chef|
			chef.cookbooks_path = "cookbooks"
			chef.add_recipe "cell-dev"
			chef.json = {
				"nodejs" => {
					"version" => "0.10.10",
					"install_method" => "binary",
					"checksum_linux_x64" => "ab42335b0e6e45bac62823d995d8062e9ba0344bc416c76a263a5e45773b2e7d"
				},
				
				"mongodb" => {
					"package_version" => "2.4.4"
				},
				
				"npm_packages" => [ "express@3.2.6", "mocha@1.11.0", "cucumber@0.3.0", "nodemon@0.7.8" ],
				
				"phantomjs" => {
					"version" => "1.9.0"
				}
			}
		end
	end
end
